// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	datachannel "github.com/steveh/ecstoolkit/datachannel"
	message "github.com/steveh/ecstoolkit/message"

	mock "github.com/stretchr/testify/mock"

	retry "github.com/steveh/ecstoolkit/retry"

	time "time"
)

// IDataChannel is an autogenerated mock type for the IDataChannel type
type IDataChannel struct {
	mock.Mock
}

type IDataChannel_Expecter struct {
	mock *mock.Mock
}

func (_m *IDataChannel) EXPECT() *IDataChannel_Expecter {
	return &IDataChannel_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *IDataChannel) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IDataChannel_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type IDataChannel_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *IDataChannel_Expecter) Close() *IDataChannel_Close_Call {
	return &IDataChannel_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *IDataChannel_Close_Call) Run(run func()) *IDataChannel_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IDataChannel_Close_Call) Return(_a0 error) *IDataChannel_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IDataChannel_Close_Call) RunAndReturn(run func() error) *IDataChannel_Close_Call {
	_c.Call.Return(run)
	return _c
}

// EstablishSessionType provides a mock function with given fields: ctx, sessionType, sleepInterval, timeoutHandler
func (_m *IDataChannel) EstablishSessionType(ctx context.Context, sessionType string, sleepInterval time.Duration, timeoutHandler func(context.Context) error) (string, error) {
	ret := _m.Called(ctx, sessionType, sleepInterval, timeoutHandler)

	if len(ret) == 0 {
		panic("no return value specified for EstablishSessionType")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration, func(context.Context) error) (string, error)); ok {
		return rf(ctx, sessionType, sleepInterval, timeoutHandler)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration, func(context.Context) error) string); ok {
		r0 = rf(ctx, sessionType, sleepInterval, timeoutHandler)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration, func(context.Context) error) error); ok {
		r1 = rf(ctx, sessionType, sleepInterval, timeoutHandler)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IDataChannel_EstablishSessionType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EstablishSessionType'
type IDataChannel_EstablishSessionType_Call struct {
	*mock.Call
}

// EstablishSessionType is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionType string
//   - sleepInterval time.Duration
//   - timeoutHandler func(context.Context) error
func (_e *IDataChannel_Expecter) EstablishSessionType(ctx interface{}, sessionType interface{}, sleepInterval interface{}, timeoutHandler interface{}) *IDataChannel_EstablishSessionType_Call {
	return &IDataChannel_EstablishSessionType_Call{Call: _e.mock.On("EstablishSessionType", ctx, sessionType, sleepInterval, timeoutHandler)}
}

func (_c *IDataChannel_EstablishSessionType_Call) Run(run func(ctx context.Context, sessionType string, sleepInterval time.Duration, timeoutHandler func(context.Context) error)) *IDataChannel_EstablishSessionType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration), args[3].(func(context.Context) error))
	})
	return _c
}

func (_c *IDataChannel_EstablishSessionType_Call) Return(_a0 string, _a1 error) *IDataChannel_EstablishSessionType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IDataChannel_EstablishSessionType_Call) RunAndReturn(run func(context.Context, string, time.Duration, func(context.Context) error) (string, error)) *IDataChannel_EstablishSessionType_Call {
	_c.Call.Return(run)
	return _c
}

// GetAgentVersion provides a mock function with no fields
func (_m *IDataChannel) GetAgentVersion() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAgentVersion")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IDataChannel_GetAgentVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAgentVersion'
type IDataChannel_GetAgentVersion_Call struct {
	*mock.Call
}

// GetAgentVersion is a helper method to define mock.On call
func (_e *IDataChannel_Expecter) GetAgentVersion() *IDataChannel_GetAgentVersion_Call {
	return &IDataChannel_GetAgentVersion_Call{Call: _e.mock.On("GetAgentVersion")}
}

func (_c *IDataChannel_GetAgentVersion_Call) Run(run func()) *IDataChannel_GetAgentVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IDataChannel_GetAgentVersion_Call) Return(_a0 string) *IDataChannel_GetAgentVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IDataChannel_GetAgentVersion_Call) RunAndReturn(run func() string) *IDataChannel_GetAgentVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionProperties provides a mock function with no fields
func (_m *IDataChannel) GetSessionProperties() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSessionProperties")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// IDataChannel_GetSessionProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionProperties'
type IDataChannel_GetSessionProperties_Call struct {
	*mock.Call
}

// GetSessionProperties is a helper method to define mock.On call
func (_e *IDataChannel_Expecter) GetSessionProperties() *IDataChannel_GetSessionProperties_Call {
	return &IDataChannel_GetSessionProperties_Call{Call: _e.mock.On("GetSessionProperties")}
}

func (_c *IDataChannel_GetSessionProperties_Call) Run(run func()) *IDataChannel_GetSessionProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IDataChannel_GetSessionProperties_Call) Return(_a0 interface{}) *IDataChannel_GetSessionProperties_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IDataChannel_GetSessionProperties_Call) RunAndReturn(run func() interface{}) *IDataChannel_GetSessionProperties_Call {
	_c.Call.Return(run)
	return _c
}

// GetTargetID provides a mock function with no fields
func (_m *IDataChannel) GetTargetID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTargetID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IDataChannel_GetTargetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTargetID'
type IDataChannel_GetTargetID_Call struct {
	*mock.Call
}

// GetTargetID is a helper method to define mock.On call
func (_e *IDataChannel_Expecter) GetTargetID() *IDataChannel_GetTargetID_Call {
	return &IDataChannel_GetTargetID_Call{Call: _e.mock.On("GetTargetID")}
}

func (_c *IDataChannel_GetTargetID_Call) Run(run func()) *IDataChannel_GetTargetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IDataChannel_GetTargetID_Call) Return(_a0 string) *IDataChannel_GetTargetID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IDataChannel_GetTargetID_Call) RunAndReturn(run func() string) *IDataChannel_GetTargetID_Call {
	_c.Call.Return(run)
	return _c
}

// OpenWithRetry provides a mock function with given fields: ctx, retryParams, messageHandler, getReconnectionToken
func (_m *IDataChannel) OpenWithRetry(ctx context.Context, retryParams retry.RepeatableExponentialRetryer, messageHandler func(message.ClientMessage), getReconnectionToken datachannel.GetReconnectionToken) error {
	ret := _m.Called(ctx, retryParams, messageHandler, getReconnectionToken)

	if len(ret) == 0 {
		panic("no return value specified for OpenWithRetry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, retry.RepeatableExponentialRetryer, func(message.ClientMessage), datachannel.GetReconnectionToken) error); ok {
		r0 = rf(ctx, retryParams, messageHandler, getReconnectionToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IDataChannel_OpenWithRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenWithRetry'
type IDataChannel_OpenWithRetry_Call struct {
	*mock.Call
}

// OpenWithRetry is a helper method to define mock.On call
//   - ctx context.Context
//   - retryParams retry.RepeatableExponentialRetryer
//   - messageHandler func(message.ClientMessage)
//   - getReconnectionToken datachannel.GetReconnectionToken
func (_e *IDataChannel_Expecter) OpenWithRetry(ctx interface{}, retryParams interface{}, messageHandler interface{}, getReconnectionToken interface{}) *IDataChannel_OpenWithRetry_Call {
	return &IDataChannel_OpenWithRetry_Call{Call: _e.mock.On("OpenWithRetry", ctx, retryParams, messageHandler, getReconnectionToken)}
}

func (_c *IDataChannel_OpenWithRetry_Call) Run(run func(ctx context.Context, retryParams retry.RepeatableExponentialRetryer, messageHandler func(message.ClientMessage), getReconnectionToken datachannel.GetReconnectionToken)) *IDataChannel_OpenWithRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(retry.RepeatableExponentialRetryer), args[2].(func(message.ClientMessage)), args[3].(datachannel.GetReconnectionToken))
	})
	return _c
}

func (_c *IDataChannel_OpenWithRetry_Call) Return(_a0 error) *IDataChannel_OpenWithRetry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IDataChannel_OpenWithRetry_Call) RunAndReturn(run func(context.Context, retry.RepeatableExponentialRetryer, func(message.ClientMessage), datachannel.GetReconnectionToken) error) *IDataChannel_OpenWithRetry_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterOutputMessageHandler provides a mock function with given fields: ctx, stopHandler, onMessageHandler
func (_m *IDataChannel) RegisterOutputMessageHandler(ctx context.Context, stopHandler datachannel.Stop, onMessageHandler func([]byte)) {
	_m.Called(ctx, stopHandler, onMessageHandler)
}

// IDataChannel_RegisterOutputMessageHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterOutputMessageHandler'
type IDataChannel_RegisterOutputMessageHandler_Call struct {
	*mock.Call
}

// RegisterOutputMessageHandler is a helper method to define mock.On call
//   - ctx context.Context
//   - stopHandler datachannel.Stop
//   - onMessageHandler func([]byte)
func (_e *IDataChannel_Expecter) RegisterOutputMessageHandler(ctx interface{}, stopHandler interface{}, onMessageHandler interface{}) *IDataChannel_RegisterOutputMessageHandler_Call {
	return &IDataChannel_RegisterOutputMessageHandler_Call{Call: _e.mock.On("RegisterOutputMessageHandler", ctx, stopHandler, onMessageHandler)}
}

func (_c *IDataChannel_RegisterOutputMessageHandler_Call) Run(run func(ctx context.Context, stopHandler datachannel.Stop, onMessageHandler func([]byte))) *IDataChannel_RegisterOutputMessageHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(datachannel.Stop), args[2].(func([]byte)))
	})
	return _c
}

func (_c *IDataChannel_RegisterOutputMessageHandler_Call) Return() *IDataChannel_RegisterOutputMessageHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *IDataChannel_RegisterOutputMessageHandler_Call) RunAndReturn(run func(context.Context, datachannel.Stop, func([]byte))) *IDataChannel_RegisterOutputMessageHandler_Call {
	_c.Run(run)
	return _c
}

// RegisterOutputStreamHandler provides a mock function with given fields: handler, isSessionSpecificHandler
func (_m *IDataChannel) RegisterOutputStreamHandler(handler datachannel.OutputStreamDataMessageHandler, isSessionSpecificHandler bool) {
	_m.Called(handler, isSessionSpecificHandler)
}

// IDataChannel_RegisterOutputStreamHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterOutputStreamHandler'
type IDataChannel_RegisterOutputStreamHandler_Call struct {
	*mock.Call
}

// RegisterOutputStreamHandler is a helper method to define mock.On call
//   - handler datachannel.OutputStreamDataMessageHandler
//   - isSessionSpecificHandler bool
func (_e *IDataChannel_Expecter) RegisterOutputStreamHandler(handler interface{}, isSessionSpecificHandler interface{}) *IDataChannel_RegisterOutputStreamHandler_Call {
	return &IDataChannel_RegisterOutputStreamHandler_Call{Call: _e.mock.On("RegisterOutputStreamHandler", handler, isSessionSpecificHandler)}
}

func (_c *IDataChannel_RegisterOutputStreamHandler_Call) Run(run func(handler datachannel.OutputStreamDataMessageHandler, isSessionSpecificHandler bool)) *IDataChannel_RegisterOutputStreamHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(datachannel.OutputStreamDataMessageHandler), args[1].(bool))
	})
	return _c
}

func (_c *IDataChannel_RegisterOutputStreamHandler_Call) Return() *IDataChannel_RegisterOutputStreamHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *IDataChannel_RegisterOutputStreamHandler_Call) RunAndReturn(run func(datachannel.OutputStreamDataMessageHandler, bool)) *IDataChannel_RegisterOutputStreamHandler_Call {
	_c.Run(run)
	return _c
}

// SendFlag provides a mock function with given fields: flagType
func (_m *IDataChannel) SendFlag(flagType message.PayloadTypeFlag) error {
	ret := _m.Called(flagType)

	if len(ret) == 0 {
		panic("no return value specified for SendFlag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(message.PayloadTypeFlag) error); ok {
		r0 = rf(flagType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IDataChannel_SendFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendFlag'
type IDataChannel_SendFlag_Call struct {
	*mock.Call
}

// SendFlag is a helper method to define mock.On call
//   - flagType message.PayloadTypeFlag
func (_e *IDataChannel_Expecter) SendFlag(flagType interface{}) *IDataChannel_SendFlag_Call {
	return &IDataChannel_SendFlag_Call{Call: _e.mock.On("SendFlag", flagType)}
}

func (_c *IDataChannel_SendFlag_Call) Run(run func(flagType message.PayloadTypeFlag)) *IDataChannel_SendFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(message.PayloadTypeFlag))
	})
	return _c
}

func (_c *IDataChannel_SendFlag_Call) Return(_a0 error) *IDataChannel_SendFlag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IDataChannel_SendFlag_Call) RunAndReturn(run func(message.PayloadTypeFlag) error) *IDataChannel_SendFlag_Call {
	_c.Call.Return(run)
	return _c
}

// SendInputDataMessage provides a mock function with given fields: payloadType, inputData
func (_m *IDataChannel) SendInputDataMessage(payloadType message.PayloadType, inputData []byte) error {
	ret := _m.Called(payloadType, inputData)

	if len(ret) == 0 {
		panic("no return value specified for SendInputDataMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(message.PayloadType, []byte) error); ok {
		r0 = rf(payloadType, inputData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IDataChannel_SendInputDataMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendInputDataMessage'
type IDataChannel_SendInputDataMessage_Call struct {
	*mock.Call
}

// SendInputDataMessage is a helper method to define mock.On call
//   - payloadType message.PayloadType
//   - inputData []byte
func (_e *IDataChannel_Expecter) SendInputDataMessage(payloadType interface{}, inputData interface{}) *IDataChannel_SendInputDataMessage_Call {
	return &IDataChannel_SendInputDataMessage_Call{Call: _e.mock.On("SendInputDataMessage", payloadType, inputData)}
}

func (_c *IDataChannel_SendInputDataMessage_Call) Run(run func(payloadType message.PayloadType, inputData []byte)) *IDataChannel_SendInputDataMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(message.PayloadType), args[1].([]byte))
	})
	return _c
}

func (_c *IDataChannel_SendInputDataMessage_Call) Return(_a0 error) *IDataChannel_SendInputDataMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IDataChannel_SendInputDataMessage_Call) RunAndReturn(run func(message.PayloadType, []byte) error) *IDataChannel_SendInputDataMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function with given fields: input, inputType
func (_m *IDataChannel) SendMessage(input []byte, inputType int) error {
	ret := _m.Called(input, inputType)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, int) error); ok {
		r0 = rf(input, inputType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IDataChannel_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type IDataChannel_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - input []byte
//   - inputType int
func (_e *IDataChannel_Expecter) SendMessage(input interface{}, inputType interface{}) *IDataChannel_SendMessage_Call {
	return &IDataChannel_SendMessage_Call{Call: _e.mock.On("SendMessage", input, inputType)}
}

func (_c *IDataChannel_SendMessage_Call) Run(run func(input []byte, inputType int)) *IDataChannel_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(int))
	})
	return _c
}

func (_c *IDataChannel_SendMessage_Call) Return(_a0 error) *IDataChannel_SendMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IDataChannel_SendMessage_Call) RunAndReturn(run func([]byte, int) error) *IDataChannel_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewIDataChannel creates a new instance of IDataChannel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDataChannel(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDataChannel {
	mock := &IDataChannel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
