// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IWebSocketChannel is an autogenerated mock type for the IWebSocketChannel type
type IWebSocketChannel struct {
	mock.Mock
}

type IWebSocketChannel_Expecter struct {
	mock *mock.Mock
}

func (_m *IWebSocketChannel) EXPECT() *IWebSocketChannel_Expecter {
	return &IWebSocketChannel_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *IWebSocketChannel) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IWebSocketChannel_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type IWebSocketChannel_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *IWebSocketChannel_Expecter) Close() *IWebSocketChannel_Close_Call {
	return &IWebSocketChannel_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *IWebSocketChannel_Close_Call) Run(run func()) *IWebSocketChannel_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IWebSocketChannel_Close_Call) Return(_a0 error) *IWebSocketChannel_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IWebSocketChannel_Close_Call) RunAndReturn(run func() error) *IWebSocketChannel_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetChannelToken provides a mock function with no fields
func (_m *IWebSocketChannel) GetChannelToken() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetChannelToken")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IWebSocketChannel_GetChannelToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannelToken'
type IWebSocketChannel_GetChannelToken_Call struct {
	*mock.Call
}

// GetChannelToken is a helper method to define mock.On call
func (_e *IWebSocketChannel_Expecter) GetChannelToken() *IWebSocketChannel_GetChannelToken_Call {
	return &IWebSocketChannel_GetChannelToken_Call{Call: _e.mock.On("GetChannelToken")}
}

func (_c *IWebSocketChannel_GetChannelToken_Call) Run(run func()) *IWebSocketChannel_GetChannelToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IWebSocketChannel_GetChannelToken_Call) Return(_a0 string) *IWebSocketChannel_GetChannelToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IWebSocketChannel_GetChannelToken_Call) RunAndReturn(run func() string) *IWebSocketChannel_GetChannelToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetStreamURL provides a mock function with no fields
func (_m *IWebSocketChannel) GetStreamURL() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStreamURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IWebSocketChannel_GetStreamURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStreamURL'
type IWebSocketChannel_GetStreamURL_Call struct {
	*mock.Call
}

// GetStreamURL is a helper method to define mock.On call
func (_e *IWebSocketChannel_Expecter) GetStreamURL() *IWebSocketChannel_GetStreamURL_Call {
	return &IWebSocketChannel_GetStreamURL_Call{Call: _e.mock.On("GetStreamURL")}
}

func (_c *IWebSocketChannel_GetStreamURL_Call) Run(run func()) *IWebSocketChannel_GetStreamURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IWebSocketChannel_GetStreamURL_Call) Return(_a0 string) *IWebSocketChannel_GetStreamURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IWebSocketChannel_GetStreamURL_Call) RunAndReturn(run func() string) *IWebSocketChannel_GetStreamURL_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function with no fields
func (_m *IWebSocketChannel) Open() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IWebSocketChannel_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type IWebSocketChannel_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
func (_e *IWebSocketChannel_Expecter) Open() *IWebSocketChannel_Open_Call {
	return &IWebSocketChannel_Open_Call{Call: _e.mock.On("Open")}
}

func (_c *IWebSocketChannel_Open_Call) Run(run func()) *IWebSocketChannel_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IWebSocketChannel_Open_Call) Return(_a0 error) *IWebSocketChannel_Open_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IWebSocketChannel_Open_Call) RunAndReturn(run func() error) *IWebSocketChannel_Open_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function with given fields: input, inputType
func (_m *IWebSocketChannel) SendMessage(input []byte, inputType int) error {
	ret := _m.Called(input, inputType)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, int) error); ok {
		r0 = rf(input, inputType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IWebSocketChannel_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type IWebSocketChannel_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - input []byte
//   - inputType int
func (_e *IWebSocketChannel_Expecter) SendMessage(input interface{}, inputType interface{}) *IWebSocketChannel_SendMessage_Call {
	return &IWebSocketChannel_SendMessage_Call{Call: _e.mock.On("SendMessage", input, inputType)}
}

func (_c *IWebSocketChannel_SendMessage_Call) Run(run func(input []byte, inputType int)) *IWebSocketChannel_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(int))
	})
	return _c
}

func (_c *IWebSocketChannel_SendMessage_Call) Return(_a0 error) *IWebSocketChannel_SendMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IWebSocketChannel_SendMessage_Call) RunAndReturn(run func([]byte, int) error) *IWebSocketChannel_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SetChannelToken provides a mock function with given fields: channelToken
func (_m *IWebSocketChannel) SetChannelToken(channelToken string) {
	_m.Called(channelToken)
}

// IWebSocketChannel_SetChannelToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetChannelToken'
type IWebSocketChannel_SetChannelToken_Call struct {
	*mock.Call
}

// SetChannelToken is a helper method to define mock.On call
//   - channelToken string
func (_e *IWebSocketChannel_Expecter) SetChannelToken(channelToken interface{}) *IWebSocketChannel_SetChannelToken_Call {
	return &IWebSocketChannel_SetChannelToken_Call{Call: _e.mock.On("SetChannelToken", channelToken)}
}

func (_c *IWebSocketChannel_SetChannelToken_Call) Run(run func(channelToken string)) *IWebSocketChannel_SetChannelToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *IWebSocketChannel_SetChannelToken_Call) Return() *IWebSocketChannel_SetChannelToken_Call {
	_c.Call.Return()
	return _c
}

func (_c *IWebSocketChannel_SetChannelToken_Call) RunAndReturn(run func(string)) *IWebSocketChannel_SetChannelToken_Call {
	_c.Run(run)
	return _c
}

// SetOnError provides a mock function with given fields: onErrorHandler
func (_m *IWebSocketChannel) SetOnError(onErrorHandler func(error)) {
	_m.Called(onErrorHandler)
}

// IWebSocketChannel_SetOnError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOnError'
type IWebSocketChannel_SetOnError_Call struct {
	*mock.Call
}

// SetOnError is a helper method to define mock.On call
//   - onErrorHandler func(error)
func (_e *IWebSocketChannel_Expecter) SetOnError(onErrorHandler interface{}) *IWebSocketChannel_SetOnError_Call {
	return &IWebSocketChannel_SetOnError_Call{Call: _e.mock.On("SetOnError", onErrorHandler)}
}

func (_c *IWebSocketChannel_SetOnError_Call) Run(run func(onErrorHandler func(error))) *IWebSocketChannel_SetOnError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(error)))
	})
	return _c
}

func (_c *IWebSocketChannel_SetOnError_Call) Return() *IWebSocketChannel_SetOnError_Call {
	_c.Call.Return()
	return _c
}

func (_c *IWebSocketChannel_SetOnError_Call) RunAndReturn(run func(func(error))) *IWebSocketChannel_SetOnError_Call {
	_c.Run(run)
	return _c
}

// SetOnMessage provides a mock function with given fields: onMessageHandler
func (_m *IWebSocketChannel) SetOnMessage(onMessageHandler func([]byte)) {
	_m.Called(onMessageHandler)
}

// IWebSocketChannel_SetOnMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOnMessage'
type IWebSocketChannel_SetOnMessage_Call struct {
	*mock.Call
}

// SetOnMessage is a helper method to define mock.On call
//   - onMessageHandler func([]byte)
func (_e *IWebSocketChannel_Expecter) SetOnMessage(onMessageHandler interface{}) *IWebSocketChannel_SetOnMessage_Call {
	return &IWebSocketChannel_SetOnMessage_Call{Call: _e.mock.On("SetOnMessage", onMessageHandler)}
}

func (_c *IWebSocketChannel_SetOnMessage_Call) Run(run func(onMessageHandler func([]byte))) *IWebSocketChannel_SetOnMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func([]byte)))
	})
	return _c
}

func (_c *IWebSocketChannel_SetOnMessage_Call) Return() *IWebSocketChannel_SetOnMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *IWebSocketChannel_SetOnMessage_Call) RunAndReturn(run func(func([]byte))) *IWebSocketChannel_SetOnMessage_Call {
	_c.Run(run)
	return _c
}

// NewIWebSocketChannel creates a new instance of IWebSocketChannel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIWebSocketChannel(t interface {
	mock.TestingT
	Cleanup(func())
}) *IWebSocketChannel {
	mock := &IWebSocketChannel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
